Oryx/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'oryx'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name="index"),
    path('signup/', include('signup.urls'), name="signup"),
    path('login/', include('login.urls'), name="login"),
    path('profile/', include('profiles.urls'), name="profile"),
    # path('home/', include('home.urls'), name="home"),
    path('products/', include('productapi.urls'), name="products"),
    path('logout/', views.LogoutView, name="logout"),
    path('test/', views.TestView, name="test"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('contact-us', views.ContactView.as_view(), name="contact"),
    path('testing', views.TestView, name="test"),
    path('api/', include('api.urls'), name="api"),
    path('privacy_policy/', views.PrivacyPolicyView, name="privacy_policy"),
    path('upload', views.UploadView, name="upload"),
] 

api/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'api'

urlpatterns = [
    path('smartphoneapi/<str:name>', views.SmartphoneAPIView.as_view(), name="smartphoneAPI"),
] 

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name="home"

urlpatterns = [
    # path('', login_required(views.HomeView.as_view(), login_url='login:login'), name="home"),
    path('',views.HomeView.as_view(), name="home"),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.LoginView, name = "login")
]

profiles/urls.py
from django.urls import path
from . import views

app_name = "profile"

urlpatterns = [
    path('<str:username>', views.ProfileView, name="profile"),
    path('users/<str:user_search>', views.UserProfileViews, name="users"),
    path('settings/change_password', views.ChangePasswordView, name="change_password"),
    path('setting/forgot_password/<str:email_address>', views.ForgotPasswordView, name="forgot_password"),
]

signup/urls.py
from django.urls import path
from . import views

app_name = 'signup'

urlpatterns = [
    path('', views.SignUpView.as_view(), name="signup")
]

home/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core import validators

def Username_check(name):
    if User.objects.filter(username=name).exists():
        raise forms.ValidationError("Username Already Exists !")

def Email_check(emailed):
    if User.objects.filter(email=emailed).exists():
        raise forms.ValidationError("Email has Already been registered")

def Password_validator(password):
    if len(password) < 8:
        raise forms.ValidationError("Password must be atleast of 8 characters")

class UserForm(forms.ModelForm):
    username = forms.CharField(required=True, max_length=50,widget=forms.TextInput(attrs={'class': 'textfield form-control','placeholder': 'Username'}),validators = [validators.MinLengthValidator(1), Username_check])
    email = forms.EmailField(required=True, max_length=50,widget=forms.TextInput(attrs={'class': 'textfield form-control','placeholder': 'Email'}),validators = [validators.MinLengthValidator(1), Email_check])
    password = forms.CharField(required=True, max_length=50,widget=forms.PasswordInput(attrs={'class': 'textfield form-control','placeholder': 'Password'}),validators = [validators.MinLengthValidator(1), Password_validator,])
    confirm_password = forms.CharField(required=True, max_length=50,widget=forms.PasswordInput(attrs={'class': 'textfield form-control','placeholder': 'Re-type Password'}),validators = [validators.MinLengthValidator(1),])

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

profiles/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core import validators
from .models import UserInfo

def EmailValidator(emailed):
    if User.objects.filter(email=emailed).exists():
        raise forms.ValidationError("Email has already been Registered")


class UpdateProfileForm(forms.ModelForm):

    profile_pic = forms.ImageField(widget=forms.FileInput(attrs = {
        'class': 'profile-pic form-control btn btn-primary', 'placeholder': 'Upload a Profile Picture ...', 'accept': 'image/*'
    }), required=False)

    
    class Meta:
        model = UserInfo
        fields = ['profile_pic',]

home/views.py
from django.shortcuts import render
from django.views.generic import *
from productapi.models import Smartphone, Rated
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import reverse, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
import re

class HomeView(TemplateView):
    template_name = 'index.html'
    model = Smartphone

    def get(self, request):
        if request.user.is_authenticated:
            user_session = request.session.get('user_id')
            user_info = request.user
            
            return render(request, self.template_name, {'user': request.user})   

        return render(request, self.template_name, {'user': request.user})

            
    def post(self, request):

        if 'people-hiddenfield' in request.POST:
            user_search = request.POST.get('people-search')
            print(user_search)
            return redirect(reverse('profile:users', args=(user_search,)))

        if 'product-hiddenfield' in request.POST:
            product = Smartphone()
        
            product_search = request.POST.get('product_search').strip(' ').lower()
            product_search = re.sub(' +', ' ',product_search)
            product_company = product_search.split(' ')[0]

            if self.model.objects.filter(name__contains=product_search):
                return HttpResponseRedirect(reverse('products:products_brand', args=(product_search,)))
            else:
                if self.model.objects.filter(name__contains=product_company):
                    return HttpResponseRedirect(reverse('products:products_brand', args=(product_company,)))
                return render(request, 'product_not_found.html')

        else:
            return render(request, 'index.html', {'user': request.user}) 

        




        

login/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import *
from .forms import UserForm
from django.shortcuts import redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from profiles.models import UserInfo
import random
from django.core.mail import send_mail

def LoginView(request):

    if request.user.is_authenticated:
        return redirect(reverse('home:home',))

    else:
        users = User()
        if request.method == 'POST' and 'forgot-hiddenfield' in request.POST:
            email_address = request.POST.get('emailid')
            forgot_user_obj = UserInfo()
            forgot_user = User.objects.filter(email__exact=email_address)
            if forgot_user:
                random_code = random.randint(1000, 9999)
                forgot_user_obj = UserInfo.objects.get(Userinfo=forgot_user[0])
                forgot_user_obj.code = random_code 
                forgot_user_obj.save()
                send_mail(
                'Oryx - Reset Password',
                'Your Code for Resetting Password is : ' + ' ' + str(random_code),
                'oryxrating@gmail.com',
                [email_address],
                fail_silently=False,
                )

                return redirect(reverse('profile:forgot_password', args=(email_address,)))

            else:
                print("User not found")
                forgot_error="There is no such Email address registered"
                return render(request, 'login.html', {'forgot_error': forgot_error})

        if request.method == 'POST' and 'login-hiddenfield' in request.POST:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    login(request, user)
                    request.session['user_id'] = user.id
                    request.session.set_expiry(0)
                    pk=user.id
                    userinfo_object = UserInfo()
                    if not UserInfo.objects.filter(Userinfo = request.user).exists():
                        userinfo_object.Userinfo = request.user
                        userinfo_object.save()
                        
                    return HttpResponseRedirect(reverse('home:home',))
                else:
                    return HttpResponse("Your account is disabled !")
            
            else:
                if User.objects.filter(email=username):
                    user = User.objects.get(email=username)
                    if user.check_password(password):
                        login(request, user)
                        request.session['user_id'] = user.id
                        request.session.set_expiry(0)
                        pk=user.id
                        userinfo_object = UserInfo()
                        if not UserInfo.objects.filter(Userinfo = request.user).exists():
                            userinfo_object.Userinfo = request.user
                            userinfo_object.save()

                        return HttpResponseRedirect(reverse('home:home',))
            
                    else:
                        error = "Wrong username or Password"
                        return render(request, 'login.html', {'error': error})    

                else:
                        error = "Wrong username or Password"
                        return render(request, 'login.html', {'error': error})    
                    
                error = "Wrong username or Password"
                return render(request, 'login.html', {'error': error})
        
        else:
            return render(request, 'login.html')

profiles/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import UserInfo
from .forms import UpdateProfileForm
from django.contrib.auth.models import User
from productapi.models import Rated
from django.shortcuts import redirect, reverse



@login_required(login_url='login:login')
def ProfileView(request, username):

    if 'people-hiddenfield' in request.POST:
            user_search = request.POST.get('people-search')
            return redirect(reverse('profile:users', args=(user_search,)))

            
    user = User.objects.filter(username=username)
    user_obj = User.objects.get(username=username)
    user_info = Rated.objects.filter(user=user[0])
    user_profile = UserInfo.objects.get(Userinfo=request.user)
    form = UpdateProfileForm()

    if request.method == 'POST' and 'remove-pic-hiddenfield' in request.POST:
        user_profile.profile_pic = ''
        user_profile.save()
        return render(request, 'profile.html', {'user_data': user_obj, 'username': username, 'user_info': user_info, 'form': form})


    if request.method == 'POST' and 'profile-pic-hiddenfield' in request.POST:
        form = UpdateProfileForm(request.POST and request.FILES)
        if form.is_valid:
            if '.jpg' or '.jpeg' or '.png' in request.POST or request.FILES:
                profile_pic = request.FILES.get('profile_pic', )
                user_profile.profile_pic = profile_pic
                user_profile.save()
                return render(request, 'profile.html', {'user_data': user_obj, 'username': username, 'user_info': user_info, 'form': form})
            
            else:
                error = "Invalid Image. Try to use other format..."
                return render(request, 'profile.html', {'user_data': user_obj, 'username': username, 'user_info': user_info, 'form': form, 'error': error})

    
    return render(request, 'profile.html', {'user_data': user_obj, 'username': username, 'user_info': user_info, 'form': form})

@login_required
def UserProfileViews(request, user_search):
    user = User.objects.filter(username__startswith=user_search) or User.objects.filter(username__endswith=user_search)

    if 'people-hiddenfield' in request.POST:
            user_search = request.POST.get('people-search')
            return redirect(reverse('profile:users', args=(user_search,)))

    if user:
        count = 0
        comments_count = Rated.objects.filter(user=user[0], has_commented = True)

        for j in comments_count:
            count = count + 1

        return render(request, 'users.html', {'user_list': user, 'comments': comments_count, 'count': count})
    else:
        error = "No such User"
        return render(request, 'users.html', {'error': error})

@login_required
def ChangePasswordView(request):
    if 'people-hiddenfield' in request.POST:
            user_search = request.POST.get('people-search')
            return redirect(reverse('profile:users', args=(user_search,)))
    user = request.user
    user_obj = User.objects.get(username=request.user.username)
    if request.method == 'POST':
        new_password = request.POST.get('password')
        user_obj.set_password(new_password)
        user_obj.save()
        return redirect('home:home')

    return render(request, 'change_password.html')

def ForgotPasswordView(request, email_address):
    if request.method == 'POST':
        code = request.POST.get('code')
        new_password = request.POST.get('password')
        user = User.objects.get(email__exact=email_address)
        user_obj = UserInfo.objects.get(Userinfo=user)
        if int(code) == int(user_obj.code):
            user.set_password(new_password)
            user.save()
            user_obj.code = 0
            user_obj.save()
            return redirect('login:login')
        else:
            code_error = "Invalid Code"
            return render(request, 'forgot_password.html', {'code_error': code_error})
    return render(request, 'forgot_password.html')

signup/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import *
from .forms import UserForm
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from productapi.models import Smartphone, Rated
from profiles.models import UserInfo

class SignUpView(FormView):
    form_class = UserForm
    user_obj = User
    template_name = 'signup.html'
    model = Smartphone
    

    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home:home',))
        else:
            i=0
            top_two = []
            top_four = []
            best_smartphones = self.model.objects.all().order_by('-total_ratings')
            for i in range(0, 2):
                top_two.append(best_smartphones[i])

            for i in range(2, 4):
                top_four.append(best_smartphones[i])
            
            form = self.form_class(None)
            return render(request, self.template_name, {'form' : form, 'top_two': top_two, 'top_four': top_four})

    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username'].lower()
            email = form.cleaned_data['email'].lower()
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']
            if confirm_password != password:
                form.add_error('confirm_password', 'Passwords Donot Match !')
                top_two = []
                top_four = []
                best_smartphones = self.model.objects.all().order_by('-total_ratings')
                for i in range(0, 2):
                    top_two.append(best_smartphones[i])

                for i in range(2, 4):
                    top_four.append(best_smartphones[i])

                return render(request, self.template_name, {'form' : form, 'top_two': top_two, 'top_four': top_four})
            else:
                top_two = []
                top_four = []
                best_smartphones = self.model.objects.all().order_by('-total_ratings')
                for i in range(0, 2):
                    top_two.append(best_smartphones[i])

                for i in range(2, 4):
                    top_four.append(best_smartphones[i])
                user.set_password(password)
                user.save()

            return redirect('login:login')
        else:
            i=0
            top_two = []
            top_four = []
            best_smartphones = self.model.objects.all().order_by('-total_ratings')
            for i in range(0, 2):
                top_two.append(best_smartphones[i])

            for i in range(2, 4):
                top_four.append(best_smartphones[i])
            return render(request, self.template_name, {'form' : form, 'top_two': top_two, 'top_four': top_four})

templates/change_password.html
{% extends 'base.html' %} {% load staticfiles %} {% block title %} OryxRating &nbsp; | &nbsp; Change Password {% endblock title %} {% block head %}
<link rel="stylesheet" href="{% static 'css/change_password.css' %}"> {% endblock head %} {% block brand-icon %}
<a href="{% url 'home:home' %}" class="navbar-brand"><img src="{% static 'OryxLogo2.png' %}" class="logo" width=27 height=27>
</a>
{% endblock brand-icon %} {% block body %}
<div class="container-fluid full-container">
    <div class="row text-center">
        <div class="col-lg-4">
        </div>

        <div class="col-lg-4 form-column text-center">
            <form class="form-control change_password_form text-center" method="POST">
                {% csrf_token %}
                <b><h3>Change Password</h3></b>
                <div class="error alert-danger" id="error">

                </div>
                <input type="password" class="textfield" id="password" placeholder="New Password" name="password">
                <p></p>
                <input type="password" class="textfield" id="confirm_password" placeholder="Confirm Password">
                <p></p>
                <input type="submit" class="btn btn-danger" value="Change Password" onclick="return Validation()">
            </form>
        </div>

        <div class="col-lg-4"></div>
    </div>

</div>

<script>
    function Validation() {

        if (document.getElementById('password').value.length < 8) {
            document.getElementById('error').innerHTML = 'Password must be of atleast 8 characters.';
            document.getElementById('password').focus();
            return false;
        }

        if (document.getElementById('password').value != document.getElementById('confirm_password').value) {
            document.getElementById('error').innerHTML = 'Passwords Donot Match';
            document.getElementById('password').focus();
            return false;
        }

        return true;
    }
</script>

{% endblock body %}

templates/home.html
{% extends 'base.html' %} {% load staticfiles %} {% block title %} OryxRating &nbsp; | &nbsp; Home {% endblock title %} {% block head %}
<link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/home.css' %}"> {% endblock head %}{% if user.is_authenticated %} {% block brand-icon %}
<a href="{% url 'home:home' %}" class="navbar-brand"><img src="{% static 'OryxLogo2.png' %}" class="logo" width=27 height=27>
</a> {% endblock brand-icon %} {% endif %} {% block navbar-items %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'profile:profile' user.username %}">Profile</a>
        <a class="dropdown-item" href="{% url 'profile:change_password' %}">Change Password</a>
    </div>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
</li>
<form class="form-inline my-2 my-lg-0 search-people" method="POST">
    {% csrf_token %}
    <input class="form-control mr-sm-2" type="search" placeholder="Search People" id="people-search" name="people-search">
    <input type="hidden" name="people-hiddenfield">
    <input type="submit" class="btn btn-outline-success my-2 my-sm-0" value="Search" onclick="return StringCheck()">
</form>
{% endblock navbar-items %} {% block body %}

<div class="container full-container">
    <div class="main-container">

        <div class="row name-heading-row text-center pt-5">
            <div class="col-lg-12 col-sm-12">
                <h1 class="name-heading">Welcome <span class="name">{{ user.username }}</span></h1>
            </div>
        </div>

        <div class="row heading-row text-center pb-5 pt-5">
            <div class="col-lg-12 col-sm-12">
                <h1 class="heading">Search Any Product</h1>
            </div>
        </div>

        <div class="row error-row text-center">
            <div class="col-lg-12">
                <h3 class="error">
                    {{ error }}
                </h3>
            </div>
        </div>

        <form method="POST" class="search-form form-horizontal">
            {% csrf_token %}
            <div class="row search-row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6 col-sm-12 search-columns">
                    <input type="text" class="search form-control text-center" name="product_search" placeholder="Search, eg: Samsung j6, xiaomi redmi note 5, apple iphone 6s" class="product_brand" id="product_brand">
                </div>
                <input type="hidden" name="product-hiddenfield">
                <div class="col-lg-3"></div>
            </div>

            <div class="row search-button-row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <input type="submit" class="btn btn-block btn-success search-button" value="Search">
                </div>
                <div class="col-lg-3"></div>
            </div>
        </form>
    </div>


    <script>
        function StringCheck() {
            if (document.getElementById('people-search').value.length == 0) {
                document.getElementById('people-search').style.border = '2px solid red';
                document.getElementById('people-search').focus
                return false;
            }
            return true;
        }
    </script>


    {% endblock body %}

templates/index.html
{% extends 'base.html' %} {% load staticfiles %} {% block title %} Oryx &nbsp; | &nbsp; Product Rating Platform {% endblock title %} {% block head %}
<link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/index.css' %}"> {% endblock head %}{% if user.is_authenticated %} {% block brand-icon %}
<a href="{% url 'home:home' %}" class="navbar-brand"><img src="{% static 'OryxLogo2.png' %}" class="logo" width=27 height=27>
</a> {% endblock brand-icon %} {% endif %} {% block navbar-items %} {% if user.is_authenticated %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="username-text">{{ user.username }}</span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'profile:profile' user.username %}">Profile</a>
        <a class="dropdown-item" href="{% url 'profile:change_password' %}">Change Password</a>
    </div>
</li>
<li class="nav-item">
    <form class="form-inline my-2 my-lg-0 search-people" method="POST">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search People" id="people-search" name="people-search">
        <input type="hidden" name="people-hiddenfield">
        <input type="submit" class="btn btn-success search-button" value="Search">
    </form>
</li>

{% else %}
</ul>
<ul class="navbar-nav register-links">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login:login' %}">Log In</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'signup:signup' %}">Sign Up</a>
    </li>
</ul>
{% endif %} {% endblock navbar-items %} {% block body %}

<div class="container full-container">
    <div class="main-container">

        <div class="row name-heading-row text-center pt-5">
            <div class="col-lg-12 col-sm-12">
                <h1 class="name-heading">Welcome To OryxRating</h1>
            </div>
        </div>

        <!-- <span class="name">{{ user.username }}</span> -->
        <div class="row heading-row text-center pb-5 pt-5">
            <div class="col-lg-12 col-sm-12">
                <h1 class="heading">Search Any Smartphone</h1>
            </div>
        </div>

        <div class="row error-row text-center">
            <div class="col-lg-12">
                <h3 class="error">
                    {{ error }}
                </h3>
            </div>
        </div>

        <form method="POST" class="search-form form-horizontal">
            {% csrf_token %}
            <div class="row search-row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6 col-sm-12 search-columns">
                    <input type="text" class="search form-control text-center" name="product_search" placeholder="Search, eg: Samsung j6, xiaomi redmi note 5, apple iphone 6s" class="product_brand" id="product_brand">
                </div>
                <input type="hidden" name="product-hiddenfield">
                <div class="col-lg-3"></div>
            </div>

            <div class="row search-button-row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <input type="submit" class="btn btn-block btn-success search-button" value="Search">
                </div>
                <div class="col-lg-3"></div>
            </div>
        </form>
    </div>


    {% endblock body %}

templates/upload.html
{% extends 'base.html' %} {% load staticfiles %} {% block title %} Products {% endblock title %} {% block head %} {% endblock head %}{% if user.is_authenticated %} {% block brand-icon %}
<a href="{% url 'home:home' %}" class="navbar-brand"><img src="{% static 'OryxLogo2.png' %}" class="logo" width=27 height=27>
</a> {% endblock brand-icon %} {% endif %} {% block navbar-items %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'profile:profile' user.username %}">Profile</a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
</li>
{% endblock navbar-items %}{% block body %}
<button class="btn btn-success" type="submit">Upload Data</button> {% endblock body %}

templates/users.html
{% extends 'base.html' %} {% load staticfiles %} {% block title %} Products {% endblock title %} {% block head %}
<link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'css/users.css' %}"> {% endblock head %}{% if user.is_authenticated %} {% block brand-icon %}
<a href="{% url 'home:home' %}" class="navbar-brand"><img src="{% static 'OryxLogo2.png' %}" class="logo" width=27 height=27>
</a> {% endblock brand-icon %} {% endif %} {% block navbar-items %} {% if user.is_authenticated %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="username-text">{{ user.username }}</span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'profile:profile' user.username %}">Profile</a>
        <a class="dropdown-item" href="{% url 'profile:change_password' %}">Change Password</a>
    </div>
</li>
<li class="nav-item">
    <form class="form-inline my-2 my-lg-0 search-people" method="POST">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search People" id="people-search" name="people-search">
        <input type="hidden" name="people-hiddenfield">
        <input type="submit" class="btn btn-success search-button" value="Search">
    </form>
</li>

{% else %}
</ul>
<ul class="navbar-nav register-links">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login:login' %}">Log In</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'signup:signup' %}">Sign Up</a>
    </li>
</ul>
{% endif %} {% endblock navbar-items %}{% block body %}
<div class="container-fluid full-container">
    <div class="row heading-row text-center p-4">
        <div class="col-lg-12">
            <h1 class="heading-title">Search Results</h1>
        </div>
    </div>

    {% if error %}
    <div class="row text-center">
        <div class="col-lg-12">
            <h1>{{ error }}</h1>
        </div>
    </div>
    {% endif %} {% for user in user_list %}
    <hr>
    <div class="row people-row p-2">
        <div class="col-4"></div>
        <div class="col-4 dp-column">
            {% if user.info.profile_pic %}
            <img src="{{ user.info.profile_pic.url }}" alt="Profile Pic" class="dp"> {% else %}
            <i class="material-icons icon-image">person</i><br> {% endif %}
        </div>
        <div class="col-4"></div>

    </div>

    <div class="people-row row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <a href="{% url 'profile:profile' user.username %}" class="user-info-text">{{ user.username }}</a>
            <p>Email : {{ user.email }}</p>
            <p>Comments : {{ count }}

            </p>
        </div>
        <div class="col-lg-4"></div>
    </div>
    <hr> {% endfor %}
</div>

{% endblock body %}